[package]
name = "rs_todo_manager"
version = "0.0.1"
edition = "2024"

[dependencies]
toasty = { version = "0.10.0", features = ["jiff", "sqlite"] }

tokio = { version = "1.44.0", features = ["macros", "rt-multi-thread"] }
clap = { version = "4.5.33", features = ["derive"] }
uuid = { version = "1.17.0", features = ["v4"] }
jiff = "0.2.35"

[rust]
lto = "thin"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"