[package]
name = "rs_todo_manager"
version = "0.0.1"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.3", features = ["runtime-tokio-native-tls", "sqlite"]}
tokio = { version = "1.44.0", features = ["macros", "rt-multi-thread"]}
chrono = "0.4.40"
clap = { version = "4.5.33", features = ["derive"] }

[rust]
lto = "thin"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"